export const reservedWords = {
  AND: "AND",
  OR: "OR",
  IF: "IF",
  ELSE: "ELSE",
  SWITCH: "SWITCH",
  CASE: "CASE",
  DEFAULT: "DEFAULT",
  BREAK: "BREAK",
  FOR: "FOR",
  var: "var",
  bool: "bool_TYPE",
  string: "string_TYPE",
  number: "number_TYPE",
  true: "true",
  false: "false",
};
